### ISSUE TITLE
giving error with jsreport-core 

### ISSUE THREAD

**Issue by mayuradesh** [jsreport/jsreport-browser-client#5]
Hi,

I am using jsreport-core package in my meteor app to generate reports.
Normally I use the "html" as "recipe" and it suffices.

Now I want to include filter option in my report.
Accordingly I want to use "recipe" as "html-with-browser-client".

For doing so I have added "jsreport-browser-client" package.

But I am getting error as :
**

TypeError: Cannot read property 'baseUrl' of undefined
at Object.recipe ..\node_modules\jsreport-browser-client\lib\browser.js
at invokeRender ..\jsreport-core\lib\render\render.js

**

I made a new post on jsreport forum and got to know that I need to additionally use "jsreport-express".
https://forum.jsreport.net/topic/1105/can-i-use-html-with-browser-client-recipe-with-jsreport-core-package/3

var jsreport = require('jsreport-core')();
jsreport.use(require('jsreport-templates')());
jsreport.use(require('jsreport-handlebars')());
jsreport.use(require('jsreport-browser-client')());
jsreport.use(require('jsreport-express')({ httpPort: 2000}));

I tried still getting same error.

**Comment by bjrmatos** [comment]
i will close this in favor of the duplicated issue jsreport/jsreport-core#47. let's move the conversation there
