### ISSUE TITLE
Full text of scripts appended to final output

### ISSUE THREAD

**Issue by InfinityTotality** [jsreport/jsreport-browser-client#6]
I was looking through the source of a rendered template, and I noticed that the full text of all scripts is included in the jsreport.template object that is automatically appended. I was under the impression that the scripts would be run on the server, hidden from the end user, and simply provide data to the template to render. As such, I have a script to define secrets for the SQL connection. Now I realize that the secrets are being sent to the client on every page load. If the scripts need to be provided to the client in full, how can I securely read the data on the server and only send the result to the client? Read the secrets from file synchronously? My template includes calls to jsreport.render to render sub-reports in frames after the user makes some selections, so I believe I am using the correct recipe here.

**Comment by pofider** [comment]
Hi,

thank you for the question. This looks like a valid point.
I cannot remember why we expose the whole template, we will discuss this through internally and come back to you.

At this moment I would propose these solutions:
1. Use environment variables to pass the secrets to the jsreport and then use `process.env` in your scripts.
2. Extract the secrets to an jsreport asset and use it as a config which you extract in the script
3. Add afterRender to your script and use regexp to remove `jsreport.template=.....;` from the `res.content`

**Comment by InfinityTotality** [comment]
Ha, 3 is interesting as a quick fix. In testing, nothing seems to be broken with the template removed. I quite like the first option however. I think I'll use that as the proper approach for my report. If there could be an option to omit the template similar to omitDataFromOutput, that might be a good change here. Assuming that wouldn't break anything.

**Comment by pofider** [comment]
We no longer do this in jsreport v3 so no need to use an extra script.
